const $ = id => document.getElementById(id);
const GEO = 'https://geocoding-api.open-meteo.com/v1/search';
const WEATHER = 'https://api.open-meteo.com/v1/forecast';
const AIR = 'https://air-quality-api.open-meteo.com/v1/air-quality';
let unit = localStorage.getItem('wn-unit') || 'C';
let dark = localStorage.getItem('wn-theme') !== 'light';
const codes = {0:['Clear sky','☀️'],1:['Mainly clear','🌤️'],2:['Partly cloudy','⛅'],3:['Overcast','☁️'],45:['Fog','🌫️'],48:['Rime fog','🌫️'],51:['Light drizzle','🌦️'],53:['Drizzle','🌦️'],55:['Heavy drizzle','🌧️'],61:['Light rain','🌦️'],63:['Rain','🌧️'],65:['Heavy rain','🌧️'],71:['Light snow','🌨️'],73:['Snow','🌨️'],75:['Heavy snow','❄️'],80:['Rain showers','🌦️'],81:['Showers','🌧️'],82:['Heavy showers','⛈️'],95:['Thunderstorm','⛈️'],96:['Thunderstorm + hail','⛈️'],99:['Severe thunderstorm','⛈️']};
const info = c => codes[c] || ['Unknown','🌡️'];
const temp = n => Math.round(unit==='C' ? n : n*9/5+32);
const speed = n => `${Math.round(unit==='C'?n:n*.621371)} ${unit==='C'?'km/h':'mph'}`;
const time = v => new Date(v).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const day = v => new Date(v+'T12:00').toLocaleDateString([], {weekday:'short'});
function status(t, bad=false){ $('status').textContent=t; $('status').classList.toggle('bad',bad); }
function toast(t){ const e=$('toast'); e.textContent=t; e.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>e.classList.remove('show'),2400); }
async function geocode(city){ const r=await fetch(`${GEO}?name=${encodeURIComponent(city)}&count=1&language=en&format=json`); if(!r.ok) throw Error('Location search failed'); const j=await r.json(); if(!j.results?.length) throw Error('City not found'); return j.results[0]; }
async function weather(lat,lon){ const p=new URLSearchParams({latitude:lat,longitude:lon,current:'temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,weather_code,cloud_cover,pressure_msl,wind_speed_10m,wind_direction_10m',hourly:'temperature_2m,precipitation_probability,weather_code',daily:'weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,uv_index_max,precipitation_probability_max,precipitation_sum',timezone:'auto',forecast_days:'7'}); const r=await fetch(`${WEATHER}?${p}`); if(!r.ok) throw Error('Weather service unavailable'); return r.json(); }
async function air(lat,lon){ try{const p=new URLSearchParams({latitude:lat,longitude:lon,current:'pm2_5,pm10,ozone',timezone:'auto'}); const r=await fetch(`${AIR}?${p}`); return r.ok?r.json():null}catch{return null} }
async function load(lat,lon,name,country=''){ try{ status(`Scanning atmosphere around ${name}…`); const [w,a]=await Promise.all([weather(lat,lon),air(lat,lon)]); render(w,a,{name,country,lat,lon}); status(`Live forecast loaded • ${name}`); }catch(e){status(e.message,true);toast(e.message)} }
function bar(id,val,text){$(id).style.width=`${Math.max(0,Math.min(100,val))}%`; $(id.replace('Bar','Value')).textContent=text}
function render(w,a,p){ const c=w.current,d=w.daily,i=info(c.weather_code),rain=d.precipitation_probability_max?.[0]??0,uv=d.uv_index_max?.[0]??0; const comfort=Math.max(0,Math.min(100,100-Math.abs(c.temperature_2m-23)*4-Math.abs(c.relative_humidity_2m-50)*.25));
  $('place').textContent=p.country?`${p.name}, ${p.country}`:p.name; $('condition').textContent=i[0]; $('temp').textContent=temp(c.temperature_2m); $('degree').textContent='°'+unit; $('feels').textContent=temp(c.apparent_temperature)+'°'; $('humidity').textContent=c.relative_humidity_2m+'%'; $('wind').textContent=speed(c.wind_speed_10m); $('pressure').textContent=Math.round(c.pressure_msl)+' hPa'; $('visibility').textContent='10 km';
  $('statTemp').textContent=temp(c.temperature_2m)+'°'; $('statHum').textContent=c.relative_humidity_2m+'%'; $('statWind').textContent=speed(c.wind_speed_10m); $('statPressure').textContent=Math.round(c.pressure_msl)+' hPa'; $('statUV').textContent=uv.toFixed(1); $('minmax').textContent=`Min: ${temp(d.temperature_2m_min[0])}° / Max: ${temp(d.temperature_2m_max[0])}°`; $('humText').textContent=comfort>65?'Comfortable':'A little humid'; $('windText').textContent=c.wind_speed_10m<15?'Light Breeze':c.wind_speed_10m<30?'Moderate Breeze':'Windy'; $('uvText').textContent=uv>=7?'High • use sunscreen':uv>=3?'Moderate exposure':'Low exposure'; $('precip').textContent=(c.precipitation??0)+' mm'; $('winddir').textContent=Math.round(c.wind_direction_10m)+'°'; $('cloud').textContent=c.cloud_cover+'%'; $('coords').textContent=`${Number(p.lat).toFixed(2)}, ${Number(p.lon).toFixed(2)}`; $('sunrise').textContent=time(d.sunrise[0]); $('sunset').textContent=time(d.sunset[0]); $('humRing').style.setProperty('--p',c.relative_humidity_2m+'%'); $('humRing').querySelector('b').textContent=c.relative_humidity_2m+'%'; document.querySelector('.compass i').style.transform=`rotate(${c.wind_direction_10m}deg)`;
  $('insightTitle').textContent=rain>65?'Carry an umbrella ☂':uv>=7?'Sun protection advised':comfort>=70?'Good afternoon! 👋':'Mixed conditions'; $('insightText').textContent=`It’s ${i[0].toLowerCase()} at ${temp(c.temperature_2m)}°. ${rain>65?`Rain probability is around ${rain}% today.`:'Conditions look reasonably comfortable for most outdoor plans.'}`; $('tip').textContent=rain>65?'✦ Umbrella mode: activated.':uv>=7?'✦ UV is elevated — use sun protection.':'✦ Atmosphere looks friendly for outdoor plans.'; bar('comfortBar',comfort,Math.round(comfort)+'%'); bar('rainBar',rain,rain+'%'); bar('uvBar',Math.min(100,uv*10),uv.toFixed(1));
  $('hours').innerHTML=''; let start=Math.max(0,w.hourly.time.findIndex(t=>t>=c.time)); w.hourly.time.slice(start,start+12).forEach((t,n)=>{let x=start+n,ii=info(w.hourly.weather_code[x]); $('hours').insertAdjacentHTML('beforeend',`<div class="hour"><small>${n?'': 'NOW '+time(t)}</small><div class="ico">${ii[1]}</div><strong>${temp(w.hourly.temperature_2m[x])}°</strong><div class="rain">💧 ${w.hourly.precipitation_probability[x]??0}%</div></div>`) });
  $('forecast').innerHTML=d.time.map((date,n)=>{let ii=info(d.weather_code[n]);return `<div class="day"><small>${n?'': 'TODAY'}${n?day(date).toUpperCase():''}</small><div class="ico">${ii[1]}</div><strong>${temp(d.temperature_2m_max[n])}° <span>${temp(d.temperature_2m_min[n])}°</span></strong><div class="rain">💧 ${d.precipitation_probability_max[n]??0}%</div></div>`}).join('');
  if(a?.current){let pm=a.current.pm2_5??0,pm10=a.current.pm10??0,o=a.current.ozone??0,score=Math.max(1,Math.min(300,Math.round(pm*3+pm10+o/10)));let label=score<=50?'Good':score<=100?'Moderate':score<=150?'Unhealthy for sensitive groups':'Unhealthy';$('aqValue').textContent=score;$('aqLabel').textContent=label;$('aqText').textContent=score<=50?'Air quality is satisfactory.':score<=100?'Sensitive people may notice reduced air quality.':'Consider limiting prolonged outdoor activity.';$('aqMarker').style.left=Math.min(96,score/3)+'%'}else{$('aqValue').textContent='—';$('aqLabel').textContent='Unavailable';$('aqText').textContent='Air-quality data is not available.'}
  $('weatherArt').className='weather-art '+(c.is_day?'day':'night'); $('weatherArt').querySelector('.sun-art').textContent=c.is_day?'☀️':'🌙'; $('weatherArt').querySelector('.cloud-art').textContent=i[1]; document.body.dataset.weather=c.weather_code; document.body.dataset.day=c.is_day?'day':'night';
}
function modal(title,html){$('modalContent').innerHTML=`<h2>${title}</h2>${html}`;$('modal').classList.remove('hidden')}
function applyTheme(){document.body.dataset.theme=dark?'dark':'light';localStorage.setItem('wn-theme',dark?'dark':'light')}
function clock(){let d=new Date();$('dateText').textContent=d.toLocaleDateString([], {weekday:'short',day:'2-digit',month:'short',year:'numeric'});$('clockText').textContent=d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});}
$('searchForm').addEventListener('submit',async e=>{e.preventDefault();let city=$('cityInput').value.trim();if(!city)return toast('Enter a city name');try{let p=await geocode(city);await load(p.latitude,p.longitude,p.name,p.country)}catch(x){status(x.message,true);toast(x.message)}});
$('chips').addEventListener('click',async e=>{let b=e.target.closest('[data-city]');if(!b)return;$('cityInput').value=b.dataset.city;let p=await geocode(b.dataset.city);load(p.latitude,p.longitude,p.name,p.country)});
$('locationBtn').onclick=()=>{if(!navigator.geolocation)return toast('Geolocation is not supported');navigator.geolocation.getCurrentPosition(async pos=>load(pos.coords.latitude,pos.coords.longitude,'Your Location'),()=>toast('Location permission was denied'))};
$('unitBtn').onclick=()=>{unit=unit==='C'?'F':'C';localStorage.setItem('wn-unit',unit);if(window.lastW)render(window.lastW,window.lastA,window.lastP);$('unitBtn').innerHTML=unit==='C'?'<b>°C</b><span>°F</span>':'<span>°C</span><b>°F</b>'};
$('themeBtn').onclick=()=>{dark=!dark;applyTheme()};
function openAbout(){modal('About WeatherNova','<p>A futuristic live-weather dashboard built with HTML5, CSS3 and Vanilla JavaScript.</p><p>Weather data comes from Open-Meteo. No API key is required.</p><p>Built as a portfolio and learning project.</p>')}
$('aboutBtn').onclick=openAbout;
$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modal').onclick=e=>{if(e.target.id==='modal')$('modal').classList.add('hidden')};
$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{let a=b.dataset.action,t=b.dataset.target;if(t)$(t)?.scrollIntoView({behavior:'smooth'});if(a==='air')$('air-card').scrollIntoView({behavior:'smooth'});if(a==='forecast')$('weekly-section').scrollIntoView({behavior:'smooth'});if(a==='map'){if(window.lastP)window.open(`https://www.openstreetmap.org/?mlat=${window.lastP.lat}&mlon=${window.lastP.lon}#map=10/${window.lastP.lat}/${window.lastP.lon}`,'_blank');else toast('Load a city first')}if(a==='settings')modal('Settings','<p>Use the ☀/☾ button for theme and °C/°F for temperature units.</p><p>Your preferences are saved locally in this browser.</p>');if(a==='about')openAbout();$('sidebar').classList.remove('open')});
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));
const oldLoad=load; load=async(...args)=>{await oldLoad(...args);};
applyTheme(); clock(); setInterval(clock,1000);
(async()=>{try{let p=await geocode('Delhi');window.lastP={lat:p.latitude,lon:p.longitude,name:p.name,country:p.country};let w=await weather(p.latitude,p.longitude),a=await air(p.latitude,p.longitude);window.lastW=w;window.lastA=a;window.lastP={...window.lastP,lat:p.latitude,lon:p.longitude};render(w,a,window.lastP);status('Live forecast loaded • Delhi')}catch(e){status(e.message,true)}})();
